# src/app/config/settings.py
import os


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UPLOAD_DIR = os.path.join(BASE_DIR, "uploads")
OUTPUT_DIR = os.path.join(BASE_DIR, "folderisasi")
PROCESSED_IMAGES_DIR = os.path.join(BASE_DIR, "processed_images")  # Direktori baru untuk menyimpan gambar hasil

# Prioritas kategori (action-focused first, then people, animals, scenery, atmosphere)
CATEGORY_PRIORITY = ["kegiatan", "manusia", "hewan", "pemandangan", "suasana"]

# Kata kunci untuk kategori
CATEGORY_KEYWORDS = {
   "kegiatan": [
        "balancing", "biting", "bodyboarding", "camping", "carrying", "catching", "chasing", "climbing",
        "whispering", "pouring", "cooking", "cycling", "dancing", "diving", "drawing", "drilling",
        "plowing", "drinking", "eating", "lighting", "exercising", "fighting", "fishing", "frolicking",
        "towing", "hailing", "hiking", "jumping", "kayaking", "filming", "kneeling", "licking",
        "needlepointing", "lying", "painting", "petting", "playing", "posing", "pulling", "wielding",
        "crabbing", "pushing", "racing", "rappelling", "resting", "riding", "running", "sailing",
        "singing", "cranking", "sitting", "skateboarding", "skating", "skiing", "sliding", "splashing",
        "standing", "staring", "summersaulting", "swimming", "throwing", "walking", "watching", "waving",
        "working", "wrestling", "writing", "gardening", "jogging", "rowing", "stretching", "sprinting",
        "hopping", "swinging", "snowmobiling", "wakeboarding", "waterskiing", "cartwheeling", "smiling", "performing",
        "leaping", "paddling", "dribbling", "swordfighting", "paragliding", "showering", "cleaning", "kicking",
        "rolling", "pouncing", "juggling", "tackling", "punting", "blindfolding", "fetching", "hugging",
        "chewing", "waiting", "bathing", "kissing", "crying", "reading", "shooting", "biking",
        "driving", "spinning", "weaving", "protesting", "pretending", "squirting", "training", "herding",
        "breakdancing", "photographing", "collecting", "scooting", "sunbathing", "grilling", "yawning", "nursing",
        "vaulting", "browsing", "signaling", "crawling", "flexing", "barbecuing", "relaxing", "tumbling",
        "acrobating", "marching", "bouncing", "twirling", "landing", "parasailing", "kiting", "wading",
        "gesturing", "rollerblading", "grinding", "selling", "howling", "barking", "digging", "spraying",
        "sledding", "navigating", "strolling", "flipping", "peeking", "sniffing", "displaying", "rummaging",
        "emerging", "crouching", "steering", "backflipping", "screaming", "cheering", "skydiving", "battling",
        "sewing", "conversing", "launching", "grabbing", "pointing", "celebrating", "socializing", "mingling",
        "crossing", "leaning", "shouting", "gathering", "talking", "nibbling", "scaling", "executing",
        "attaching", "reaching", "touching", "whipping", "casting", "holding", "grinning", "lassoing",
        "prancing", "skipping", "looking", "competing", "arguing", "fanning", "colliding", "rushing",
        "hustling", "gliding", "trotting", "bolting", "shoveling", "meditating", "praying", "assembling",
        "burning", "snorkeling", "spreading", "flapping", "blocking", "defending", "galloping", "soaring",
        "toasting", "embracing", "reclining", "monitoring", "pinching", "navigating", "pedaling", "slamming",
        "dunking", "guarding", "stunting", "displaying", "sparkling", "twisting", "texting", "sleeping",
        "fluting", "resting", "conversing", "surfing", "lounging", "retrieving", "smiling", "posing",
        "touching", "observing", "bending", "frowning", "carving", "singing", "lifting", "checking",
        "squinting", "cringing", "tugging", "wiping", "attacking", "balancing", "vaulting", "slaloming",
        "twirling", "painting", "nuzzling", "busking", "fastening", "powerwashing", "dragging", "performing",
        "advancing", "begging", "battling", "celebrating", "mingling", "raising", "screening", "replacing",
        "sharing", "investigating", "raftering", "iceskating", "waving", "fighting", "playing", "dressing",
        "preparing", "adjusting", "crashing", "falling",
        "galloping", "trotting", "cantering", "prancing", "scooting", "tumbling", "flipping", "cartwheeling",
        "somersaulting", "vaulting", "leaping", "hopping", "skipping", "bounding", "lunging", "darting",
        "dashing", "scurrying", "scampering", "strolling", "sauntering", "trudging", "marching", "parading",
        "striding", "pacing", "swaggering", "shuffling", "waddling", "tottering", "hobbling", "limping",
        "tiptoeing", "sneaking", "slinking", "crawling", "inching", "wriggling", "squirming", "twisting",
        "turning", "spinning", "whirling", "twirling", "pirouetting", "swaying", "bobbing", "weaving",
        "dodging", "ducking", "lunging", "thrusting", "parrying", "slashing", "fencing", "sparring",
        "grappling", "tackling", "wrestling", "pinning", "lifting", "hoisting", "hauling", "dragging",
        "towing", "pulling", "yanking", "tugging", "pushing", "shoving", "nudging", "prodding",
        "poking", "tapping", "brushing", "stroking", "petting", "grooming", "feeding", "watering",
        "tending", "herding", "shepherding", "guiding", "leading", "directing", "signaling", "gesturing",
        "pointing", "waving", "beckoning", "nodding", "bowing", "curtsying", "saluting", "clapping",
        "cheering", "chanting", "shouting", "yelling", "screaming", "hollering", "whooping", "whistling",
        "singing", "humming", "crooning", "chanting", "reciting", "narrating", "storytelling", "lecturing",
        "teaching", "instructing", "coaching",
        "aiming", "interviewing", "snowboarding", "filming", "hugging", "smoking", "performing", "reading",
        "jousting", "fencing", "punching", "serving", "volleying", "galloping", "nipping", "posing",
        "smiling", "laughing", "splashing", "dunking", "blocking", "dribbling", "sliding", "grinding",
        "rushing", "sprinting", "leaping", "twirling", "balancing", "sparring", "clapping", "cheering",
        "teaching", "conversing", "gesturing", "pointing", "celebrating", "mingling", "crossing", "leaning",
        "shouting", "gathering", "chasing", "attacking", "defending", "slamming", "tossing", "spinning",
        "kicking", "striking", "paddling", "steering", "navigating", "vaulting", "soaring", "gliding",
        "trotting", "scrambling", "crawling", "scooting", "darting", "bolting", "stumbling", "tripping",
        "skidding", "slipping", "tumbling", "flipping", "somersaulting", "cartwheeling", "lunging", "dodging",
        "sculpting", "knitting", "crocheting", "embroidering", "quilting", "beading", "weaving", "spinning",
        "carpentry", "woodworking", "sanding", "polishing", "chiseling", "carving", "molding", "casting",
        "forging", "welding", "soldering", "hammering", "nailing", "screwing", "bolting", "gluing",
        "taping", "stapling", "clipping", "tying", "knotting", "braiding", "twisting", "looping",
        "stitching", "seaming", "hemming", "tailoring", "fitting", "measuring", "cutting", "slicing",
        "chopping", "dicing", "mincing", "grating", "peeling", "coring", "squeezing", "juicing",
        "blending", "mixing", "stirring", "whisking", "kneading", "rolling", "shaping", "baking",
        "roasting", "grilling", "frying", "sautéing", "boiling", "steaming", "poaching", "broiling",
        "toasting", "brewing", "fermenting", "distilling", "infusing", "marinating", "seasoning", "tasting",
        "sampling", "snacking", "munching", "nibbling", "sipping", "gulping", "chugging", "swallowing",
        "chewing", "biting", "licking", "sucking", "spitting", "gargling", "rinsing", "brushing",
        "flossing", "combing", "braiding", "curling", "straightening", "styling", "trimming", "shaving",
        "clipping", "plucking", "waxing", "tweezing", "massaging", "rubbing", "soothing", "stretching",
        "flexing", "bending", "twisting", "arching", "lunging", "squatting", "dipping", "curling",
        "pressing", "lifting", "swinging", "thrusting", "kicking", "punching", "jabbing", "hooking",
        "slapping", "smacking", "tapping", "patting", "stroking", "caressing", "tickling", "pinching",
        "squeezing", "gripping", "clutching", "grasping", "clenching", "holding", "releasing", "tossing",
        "flinging", "hurling", "throwing", "pitching", "lobbing", "passing", "handing", "delivering",
        "serving", "volleying", "smashing", "spiking", "bouncing", "dribbling", "shooting", "aiming",
        "targeting", "focusing", "zooming", "scanning", "searching", "scouting", "tracking", "following",
        "stalking", "pursuing", "chasing", "hunting", "trapping", "snaring", "netting", "fishing",
        "angling", "reeling", "casting", "trolling", "harpooning", "spearing", "gigging", "snagging",
        "diving", "plunging", "submerging", "swimming", "floating", "drifting", "bobbing", "wading",
        "splashing", "paddling", "rowing", "sailing", "cruising", "motoring", "steering", "piloting",
        "navigating", "charting", "mapping", "plotting", "surveying", "exploring", "roaming", "wandering",
        "trekking", "hiking", "climbing", "scaling", "ascending", "descending", "rappelling", "abseiling",
        "parachuting", "skydiving", "gliding", "soaring", "flying", "hovering", "buzzing", "swooping",
        "diving", "swooshing", "zipping", "zooming", "rushing", "hurrying", "hastening", "scrambling",
        "scooting", "darting", "dashing", "bolting", "fleeing", "escaping", "evading", "dodging",
        "weaving", "zigzagging", "swerving", "veering", "skidding", "sliding", "slipping", "stumbling",
        "tripping", "falling", "crashing", "colliding", "bumping", "smashing", "ramming", "slamming",
        "barreling", "charging", "storming", "raging", "battling", "clashing", "dueling", "jousting",
        "sparring", "grappling", "tackling", "wrestling", "pinning", "subduing", "restraining", "binding",
        "tying", "shackling", "handcuffing", "chaining", "locking", "securing", "fastening", "latching",
        "bolting", "sealing", "taping", "gluing", "cementing", "welding", "fusing", "joining",
        "connecting", "linking", "coupling", "hitching", "attaching", "affixing", "mounting", "installing",
        "erecting", "building", "constructing", "assembling", "fabricating", "crafting", "designing", "sketching",
        "drawing", "painting", "coloring", "shading", "outlining", "illustrating", "doodling", "scribbling",
        "writing", "typing", "composing", "drafting", "editing", "revising", "proofreading", "publishing",
        "printing", "copying", "scanning", "faxing", "emailing", "texting", "messaging", "chatting",
        "posting", "blogging", "tweeting", "sharing", "uploading", "downloading", "streaming", "broadcasting",
        "filming", "recording", "taping", "photographing", "snapping", "shooting", "capturing", "framing",
        "focusing", "zooming", "panning", "tilting", "directing", "producing", "editing", "mixing",
        "blending", "fading", "transitioning", "cutting", "splicing", "looping", "repeating", "rewinding",
        "fastforwarding", "pausing", "stopping", "playing", "performing", "acting", "miming", "impersonating",
        "imitating", "mimicking", "parodying", "satirizing", "rehearsing", "practicing", "training", "coaching",
        "mentoring", "tutoring", "instructing", "teaching", "lecturing", "presenting", "demonstrating", "showing",
        "displaying", "exhibiting", "showcasing", "revealing", "unveiling", "exposing", "uncovering", "discovering",
        "exploring", "investigating", "researching", "studying", "analyzing", "examining", "inspecting", "scrutinizing",
        "observing", "watching", "monitoring", "tracking", "surveying", "scanning", "spying", "eavesdropping",
        "listening", "hearing", "overhearing", "tuning", "adjusting", "tweaking", "fine-tuning", "calibrating",
        "balancing", "leveling", "aligning", "centering", "positioning", "placing", "arranging", "organizing",
        "sorting", "classifying", "categorizing", "grouping", "clustering", "stacking", "piling", "heaping",
        "stockpiling", "storing", "warehousing", "shelving", "filing", "archiving", "cataloging", "indexing",
        "labeling", "tagging", "marking", "branding", "engraving", "etching", "inscribing", "embossing",
        "stamping", "imprinting", "sealing", "signing", "autographing", "endorsing", "initialing", "notarizing",
        "certifying", "authenticating", "validating", "verifying", "confirming", "approving", "authorizing", "sanctioning",
        "licensing", "permitting", "allowing", "enabling", "empowering", "encouraging", "motivating", "inspiring",
        "uplifting", "cheering", "applauding", "praising", "complimenting", "congratulating", "celebrating", "honoring",
        "awarding", "rewarding", "recognizing", "acknowledging", "saluting", "toasting", "commemorating", "memorializing",
        "remembering", "recalling", "reminiscing", "reflecting", "pondering", "contemplating", "meditating", "musing",
        "daydreaming", "fantasizing", "imagining", "envisioning", "visualizing", "picturing", "dreaming", "hoping",
        "wishing", "praying", "blessing", "cursing", "swearing", "cussing", "yelling", "shouting",
        "screaming", "howling", "wailing", "moaning", "groaning", "whining", "complaining", "grumbling",
        "muttering", "mumbling", "whispering", "murmuring", "chattering", "babbling", "gibbering", "rambling",
        "ranting", "raving", "venting", "expressing", "articulating", "voicing", "pronouncing", "enunciating",
        "speaking", "talking", "conversing", "discussing", "debating", "arguing", "negotiating", "bargaining",
        "haggling", "bartering", "trading", "exchanging", "swapping", "selling", "buying", "purchasing",
        "shopping", "browsing", "window-shopping", "bidding", "auctioning", "appraising", "valuing", "assessing",
        "evaluating", "judging", "rating", "ranking", "scoring", "grading", "marking", "testing",
        "quizzing", "examining", "questioning", "interviewing", "interrogating", "probing", "inquiring", "investigating",
        "researching", "studying", "learning", "memorizing", "practicing", "rehearsing", "drilling", "training",
        "coaching", "mentoring", "guiding", "leading", "directing", "supervising", "managing", "overseeing",
        "administering", "organizing", "planning", "scheduling", "coordinating", "arranging", "orchestrating", "choreographing",
        "designing", "crafting", "creating", "inventing", "innovating", "devising", "formulating", "concocting",
        "brewing", "mixing", "blending", "stirring", "shaking", "pouring", "serving", "presenting",
        "offering", "gifting", "donating", "contributing", "volunteering", "assisting", "helping", "supporting",
        "aiding", "backing", "sponsoring", "promoting", "advocating", "championing", "defending", "protecting",
        "guarding", "shielding", "sheltering", "covering", "wrapping", "enveloping", "encasing", "boxing",
        "packing", "crating", "shipping", "delivering", "transporting", "hauling", "carting", "carrying",
        "lugging", "toting", "schlepping", "dragging", "pulling", "yanking", "tugging", "heaving",
        "hoisting", "lifting", "raising", "elevating", "boosting", "upping", "escalating", "increasing",
        "amplifying", "magnifying", "enhancing", "improving", "upgrading", "refining", "polishing", "perfecting",
        "honing", "sharpening", "tuning", "adjusting", "tweaking", "calibrating", "balancing", "aligning",
        "leveling", "straightening", "smoothing", "flattening", "pressing", "ironing", "steaming", "cleaning",
        "washing", "scrubbing", "scouring", "polishing", "buffing", "shining", "glossing", "waxing",
        "dusting", "sweeping", "mopping", "vacuuming", "raking", "shoveling", "plowing", "tilling",
        "planting", "sowing", "seeding", "cultivating", "harvesting", "reaping", "picking", "gathering",
        "collecting", "amassing", "accumulating", "stockpiling", "hoarding", "storing", "preserving", "canning",
        "pickling", "jarring", "bottling", "packaging", "labeling", "tagging", "marking", "branding",
        "advertising", "marketing", "promoting", "selling", "pitching", "presenting", "showcasing", "displaying",
        "exhibiting", "demonstrating", "illustrating", "explaining", "clarifying", "elaborating", "detailing", "describing",
        "narrating", "recounting", "relating", "reporting", "chronicling", "documenting", "recording", "logging",
        "journaling", "blogging", "vlogging", "streaming", "broadcasting", "telecasting", "airing", "transmitting",
        "relaying", "forwarding", "sending", "dispatching", "mailing", "shipping", "delivering", "distributing",
        "circulating", "spreading", "disseminating", "publishing", "releasing", "launching", "unveiling", "revealing",
        "exposing", "uncovering", "disclosing", "divulging", "announcing", "proclaiming", "declaring", "stating",
        "asserting", "affirming", "confirming", "verifying", "validating", "authenticating", "certifying", "endorsing",
        "approving", "sanctioning", "authorizing", "permitting", "allowing", "enabling", "empowering", "encouraging",
        "motivating", "inspiring", "uplifting", "elevating", "boosting", "cheering", "applauding", "praising",
        "complimenting", "congratulating", "celebrating", "honoring", "commemorating", "memorializing", "remembering", "reminiscing",
        
    ],
    "manusia": [
        "human", "person", "man", "woman", "people", "child", "boy", "girl",
        "Geisha", "adult", "individual", "group", "crowd", "family", "friend", "toddler",
        "Showgirl", "baby", "teenager", "skier", "climber", "hiker", "fisherman", "kayaker",
        "Lecturer", "skateboarder", "runner", "bicyclist", "worker", "artist", "performer", "spectator",
        "Biplane pilot", "dancer", "singer", "painter", "photographer", "tourist", "student", "elderly",
        "Fencer", "costumed person", "parent", "goalie", "jogger", "bather", "onlooker", "camper",
        "Presenter", "firefighter", "biker", "snowmobiler", "snowboarder", "paraglider", "rower", "gymnast",
        "Vampire", "surfer", "volleyball player", "basketball player", "football player", "kickboxer", "horserider", "cheerleader",
        "Werewolf", "quarterback", "coach", "referee", "drummer", "saxophonist", "mascot", "commuter",
        "protester", "carnival attendee", "reader", "bride", "groom", "cricketer", "soldier", "civilian",
        "schoolgirl", "chef", "martial artist", "monk", "clown", "acrobat", "vendor", "swimmer",
        "hockey player", "motorcyclist", "model", "athlete", "musician", "cowboy", "college student", "racer",
        "sister", "skydiver", "carnival worker", "trainer", "fan", "beachgoer", "pedestrian", "hula hooper",
        "diver", "rockstar", "father", "mother", "brother", "sister", "teen", "youth",
        "kid", "male", "female", "spectators", "audience", "passenger", "jockey", "stuntman",
        "vendor", "employee", "racer", "player", "competitor", "opponent", "teammate", "schoolboy",
        "Asian man", "Asian woman", "blonde girl", "brunette woman", "bearded man", "dark-skinned boy", "dark-skinned man", "light-skinned man",
        "light-skinned woman", "elderly man", "elderly woman", "young man", "young woman", "middle-aged woman", "middle-aged man", "costumed child",
        "costumed adult", "professional racer", "amateur racer", "team member", "band member", "Hawaiian man", "Hawaiian singer", "ethnic people",
        "costumed girl", "costumed boy", "cheerleader squad", "soccer player", "baseball player", "rugby player", "lacrosse player", "tennis player",
        "golfer", "skater", "inline skater", "BMX rider", "dirt biker", "motocross rider", "cyclist", "triathlete",
        "marathon runner", "sprinter", "walker", "hurdler", "pole vaulter", "scuba diver", "snorkeler", "synchronized swimmer",
        "water polo player", "canoeist", "yachtsman", "yachtswoman", "windsurfer", "kitesurfer", "parasailer", "hang glider",
        "bungee jumper", "base jumper", "ice climber", "mountaineer", "backpacker", "trekker", "scout", "guide",
        "ranger", "park ranger", "forest ranger", "game warden", "lifeguard", "rescuer", "first responder", "paramedic",
        "emt", "firefighter", "soldier", "marine", "sailor", "airman", "pilot", "astronaut",
        "cosmonaut", "spaceman", "spacewoman", "explorer", "adventurer", "alpinist", "caver", "snorkeler",
        "synchronized swimmer", "water polo player", "canoeist", "yachtsman", "yachtswoman", "windsurfer", "kitesurfer", "parasailer",
        "hang glider", "bungee jumper", "base jumper", "ice climber", "mountaineer", "backpacker", "trekker", "scout",
        "guide", "ranger", "park ranger", "forest ranger", "game warden", "lifeguard", "rescuer",
        "first responder", "paramedic", "emt", "firefighter", "soldier", "marine", "sailor", "airman",
        "pilot", "astronaut", "Wrestler", "Greyhound racer", "Supporter", "Mover", "Panhandler", "Violinist",
        "ballerina", "waiter", "waitress", "grandmother", "grandfather", "priest", "wedding party", "bridesmaid",
        "groomsman", "lady", "gentleman", "goalkeeper", "vendor", "driver", "juggler", "patient",
        "nurse", "security person", "city worker", "professional wrestler", "homeless man", "carnival worker", "santa claus", "boater",
        "sledder", "rollerblader", "Asian boy", "Asian girl", "blonde woman", "brunette girl", "grey-haired man", "white-bearded man",
        "toddler girl", "toddler boy", "young boy", "young girl", "middle-aged person", "costumed woman", "costumed man", "team player",
        "choir member", "flag bearer", "arcade player", "fairgoer", "art enthusiast", "market vendor", "street performer", "festival attendee",
        "game player",
        "flutist", "Muslim woman", "surfer", "sunbather", "rafter", "busker", "newlywed", "pastor",
        "wedding guest", "guitarist", "skier", "rugby player", "track athlete", "pole vaulter", "bridesmaid", "groomsman",
        "mountain biker", "sledder", "team member", "band member", "theater worker", "protester", "festivalgoer", "wedding party",
        "skater", "fire juggler", "street artist", "Asian baby", "couple", "teenage girl", "infant", "muscular man",
        "curvy woman", "blonde child", "male gymnast", "female skater",
        "jockey", "cowgirl", "cowhand", "shepherd", "farmer", "gardener", "trainer", "instructor",
        "mentor", "guide", "leader", "captain", "coach", "umpire", "judge", "referee",
        "spectator", "bystander", "onlooker", "witness", "participant", "competitor", "contestant", "opponent",
        "teammate", "rival", "champion", "athlete", "sprinter", "marathoner", "cyclist", "swimmer",
        "diver", "gymnast", "wrestler", "boxer", "fencer", "archer", "shooter", "golfer",
        "tennis player", "badminton player", "volleyball player", "soccer player", "rugby player", "cricketer", "baseball player", "softball player",
        "hockey player", "skater", "snowboarder", "surfer", "sailor", "rower", "canoeist", "kayaker",
        "windsurfer", "kitesurfer", "parasailer", "skydiver", "bungee jumper", "climber", "mountaineer", "hiker",
        "trekker", "explorer", "adventurer", "scout", "ranger", "lifeguard", "rescuer", "paramedic",
        "firefighter", "soldier", "marine", "sailor", "pilot", "astronaut", "musician", "guitarist",
        "drummer", "pianist", "violinist", "saxophonist", "flutist", "singer", "dancer", "ballerina",
        "choreographer", "actor", "actress", "performer", "juggler", "acrobat", "clown", "magician",
        "artist", "painter", "sculptor", "photographer", "videographer", "writer", "poet", "journalist",
        "reporter", "editor", "teacher", "professor", "student", "scholar", "researcher", "scientist",
        "engineer", "architect", "designer", "chef", "cook", "baker", "waiter", "waitress",
        "bartender", "vendor", "merchant", "shopkeeper", "craftsman", "artisan", "carpenter", "blacksmith",
        "mechanic", "technician", "doctor", "nurse", "surgeon", "dentist", "pharmacist", "therapist",
        "counselor", "lawyer", "judge", "police officer", "security guard", "politician", "diplomat", "ambassador",
        "monk", "nun", "priest", "pastor", "rabbi", "imam", "shaman", "healer",
        "elder", "grandparent", "parent", "sibling", "cousin", "neighbor", "friend", "colleague",
        "classmate", "tourist", "traveler", "passenger", "commuter", "pedestrian", "shopper", "customer",
        "client", "patient", "visitor", "guest", "host", "hostess", "organizer", "volunteer",
        "activist", "protester", "demonstrator", "supporter", "fan", "enthusiast", "collector", "hobbyist",
        "amateur", "professional", "veteran", "rookie", "newcomer", "local", "resident", "citizen",
        "immigrant", "refugee", "nomad", "wanderer", "vagabond", "hermit", "recluse", "celebrity",
        "influencer", "blogger", "vlogger", "streamer", "gamer", "developer", "programmer", "hacker",
        "entrepreneur", "businessman", "businesswoman", "executive", "manager", "worker", "laborer", "employee",
        "freelancer", "contractor", "consultant", "advisor", "analyst", "accountant", "banker", "investor",
        "trader", "broker", "realtor", "farmer", "rancher", "herder", "fisher", "hunter",
        "trapper", "forager", "botanist", "zoologist", "biologist", "geologist", "astronomer", "meteorologist",
        "chemist", "physicist", "mathematician", "historian", "archaeologist", "anthropologist", "sociologist", "psychologist",
        "philosopher", "theologian", "librarian", "curator", "archivist", "educator", "mentor", "tutor",
        "instructor", "trainer", "coach", "counselor", "therapist", "healer", "shaman", "medium",
        "psychic", "fortune teller", "astrologer", "palm reader", "tarot reader", "storyteller", "bard", "poet",
        "novelist", "playwright", "screenwriter", "director", "producer", "cinematographer", "editor", "sound engineer",
        "lighting technician", "stagehand", "costumer", "makeup artist", "hairdresser", "stylist", "model", "fashion designer",
        "tailor", "seamstress", "weaver", "potter", "glassblower", "jeweler", "blacksmith", "carpenter",
        "mason", "builder", "contractor", "architect", "engineer", "mechanic", "technician", "electrician",
        "plumber", "welder", "painter", "decorator", "landscaper", "groundskeeper", "caretaker", "janitor",
        "cleaner", "maid", "housekeeper", "butler", "nanny", "babysitter", "caregiver", "aide",
        "assistant", "secretary", "receptionist", "clerk", "cashier", "barista", "chef", "cook",
        "baker", "butcher", "brewer", "winemaker", "distiller", "bartender", "server", "waiter",
        "waitress", "host", "hostess", "manager", "supervisor", "foreman", "overseer", "inspector",
        "auditor", "analyst", "consultant", "advisor", "planner", "organizer", "coordinator", "facilitator",
        "mediator", "negotiator", "diplomat", "ambassador", "envoy", "representative", "delegate", "spokesperson",
        "advocate", "activist", "reformer", "revolutionary", "rebel", "dissenter", "protester", "demonstrator",
        "picketer", "striker", "unionist", "organizer", "volunteer", "philanthropist", "donor", "benefactor",
        "patron", "sponsor", "supporter", "backer", "promoter", "publicist", "marketer", "advertiser",
        "salesperson", "vendor", "merchant", "shopkeeper", "trader", "broker", "dealer", "auctioneer",
        "appraiser", "valuer", "assessor", "inspector", "surveyor", "engineer", "architect", "designer",
        "drafter", "illustrator", "animator", "cartoonist", "graphic designer", "web designer", "developer", "programmer",
        "coder", "hacker", "technologist", "innovator", "inventor", "entrepreneur", "businessman", "businesswoman",
        "executive", "manager", "director", "ceo", "cfo", "coo", "president", "vice president",
        "chairman", "chairwoman", "board member", "shareholder", "investor", "financier", "banker", "accountant",
        "bookkeeper", "auditor", "tax preparer", "financial advisor", "consultant", "analyst", "strategist", "planner",
        "advisor", "counselor", "mentor", "coach", "trainer", "instructor", "teacher", "professor",
        "educator", "tutor", "scholar", "researcher", "scientist",
        
    ],
    "hewan": [
        "animal", "dog", "cat", "bird", "fish", "horse", "elephant", "tiger",
        "lion", "puppy", "kitten", "pet", "cow", "sheep", "rabbit", "duck",
        "chicken", "goat", "pig", "monkey", "chimpanzee", "zebra", "giraffe", "beagle",
        "terrier", "labrador", "corgi", "doberman", "spaniel", "bulldog", "boxer", "calico",
        "crane", "deer", "fox", "wolf", "bear", "owl", "eagle", "parrot",
        "snake", "antelope", "wildebeest", "seagull", "pitbull", "husky", "shepherd", "pony",
        "dachshund", "poodle", "golden retriever", "weimaraner", "dalmatian", "pomeranian", "samoyed", "sled dog",
        "greyhound", "German shepherd", "French poodle", "camel", "goose", "Scottish terrier", "basset hound", "collie",
        "West Highland terrier", "German short-haired pointer", "rottweiler", "lamb", "butterfly", "bull", "coyote", "wild dog",
        "racing dog", "Australian Shepherd", "lioness", "bison", "dolphin", "killer whale", "orca", "ferret",
        "labrador retriever", "greyhound dog", "racing greyhound", "sled team", "water dog", "beach dog", "field dog", "toy tiger",
        "inflatable tiger", "hunting dog", "brown dog", "white dog", "black dog", "tan dog", "fluffy dog", "large dog",
        "small dog", "wet dog", "swan", "dog toy", "blue toy", "red collar", "orange collar", "blue collar",
        "fetching dog", "swimming dog", "running dog", "jumping dog", "racing dog team", "muzzled dog", "playful dog", "leashed dog",
        "sniffing dog", "spotted dog", "tan and black dog", "poodle", "chasing dog", "diving dog", "herding dog", "tennis ball",
        "orange ball", "green collar", "yellow dog", "small white dog", "brown and white dog", "black and white dog", "racing dogs", "dog show",
        "buffalo",
        "brown dog", "white dog", "black dog", "tan dog", "spotted dog", "muzzled dog", "herding dog", "swimming dog", 
        "jumping dog", "racing dog", "playful dog", "leashed dog", "fetching dog", "small dog", "large dog", "fluffy dog", 
        "black and white dog", "brown and white dog", "tan and black dog", "chasing dog", "diving dog", "poodle", "greyhound", "German shepherd", 
        "labrador retriever", "beagle", "terrier", "corgi", "doberman", "spaniel", "bulldog", "boxer", 
        "husky", "dachshund", "pomeranian", "samoyed", "collie", "Scottish terrier", "basset hound", "French poodle", 
        "pitbull", "weimaraner", "dalmatian", "Australian shepherd", "hunting dog", "racing greyhound", "sled dog", "water dog", 
        "beach dog", "field dog", "dog toy", "tennis ball", "orange ball", "green collar", "red collar", "blue collar", 
        "sniffing dog", "sheep", "lamb", "buffalo", "seagull", "swan", "goose", "crane", 
        "deer", "fox", "wolf", "bear", "owl", "eagle", "parrot", "snake", 
        "antelope", "wildebeest", "lion", "tiger", "elephant", "horse", "cow", "goat", 
        "pig", "monkey", "chimpanzee", "zebra", "giraffe", "rabbit", "duck", "chicken", 
        "camel", "bison", "dolphin", "killer whale", "orca", "ferret", "pony", "bull", 
        "coyote", "wild dog", "lioness", "dog show", "racing dogs",
        "turkey", "alligator", "greyhound puppy", "bumble bee", "squirrel", "donkey", "peacock", "rooster",
        "pelican", "penguin", "hawk", "falcon", "vulture", "ostrich", "emu", "kangaroo",
        "cheetah", "leopard", "panther", "jaguar", "elk", "moose", "reindeer", "badger",
        "raccoon", "skunk", "hedgehog", "porcupine", "armadillo", "tortoise", "turtle", "salamander",
        "frog", "toad", "lizard", "gecko", "chameleon", "crocodile", "hyena", "jackal",
        "meerkat", "warthog", "hippo", "rhinoceros", "gazelle", "impala", "lemur", "baboon",
        "gorilla", "orangutan", "kudu", "okapi", "ibex", "stork", "heron", "flamingo",
        "spoonbill", "albatross", "puffin", "gull", "tern", "dove", "pigeon", "sparrow",
        "finch", "robin", "thrush", "crow", "raven", "magpie", "bluejay", "cardinal",
        "woodpecker", "hummingbird", "kingfisher", "egret", "cormorant", "seal", "walrus", "manatee",
        "dugong", "jellyfish", "octopus", "squid", "starfish", "coral reef", "whale shark", "ray",
        "manta", "stingray", "seahorse", "clownfish", "barracuda", "tuna", "salmon", "cod",
        "herring", "sardine", "anchovy", "crab", "lobster", "shrimp", "prawn", "mussel",
        "oyster", "clam", "scallop", "moth", "beetle", "ladybug", "dragonfly", "grasshopper",
        "cricket", "cicada", "ant", "bee", "wasp", "hornet", "firefly", "spider",
        "tarantula", "scorpion", "centipede", "millipede", "worm", "caterpillar", "cocoon", "pupa",
        "larva", "tadpole",
        "boar", "lynx", "cougar", "ocelot", "caribou", "ant", "mosquito", "gnat",
        "swallow", "swallowtail", "macaw", "toucan", "vulture", "condor", "kiwi", "emu",
        "quail", "pheasant", "turaco", "hoopoe", "cuckoo", "nightjar", "swift", "grebe",
        "loon", "albatross", "frigatebird", "booby", "gannet", "skua", "jaeger", "auk",
        "murre", "guillemot", "puffin", "penguin", "crayfish", "barnacle", "krill", "plankton",
        "nautilus", "anemone", "coral", "urchin", "sea cucumber", "sea slug", "nudibranch", "moray",
        "eel", "grouper", "snapper", "mackerel", "marlin", "swordfish", "tarpon", "angelfish",
        "parrotfish", "triggerfish", "pufferfish", "lionfish", "stonefish", "flounder", "halibut", "sole",
        "codfish", "haddock", "pollock", "catfish", "sturgeon", "carp", "minnow", "guppy",
        "betta", "goldfish", "koi", "piranha", "barramundi", "perch", "bass", "trout",
        "char", "grayling", "muskox", "yak", "alpaca", "llama", "guanaco", "vicuna",
        "tapir", "sloth", "anteater", "pangolin", "mongoose", "meerkat", "fossa", "civet",
        "genet", "hyrax", "aardvark", "echidna", "platypus", "wallaby", "wombat", "koala",
        "quokka", "numbat", "bilby", "bandicoot", "opossum", "shrew", "mole", "vole",
        "lemming", "gerbil", "hamster", "jerboa", "capybara", "paca", "agouti", "chinchilla",
        "otter", "beaver", "muskrat", "nutria", "cormorant", "grebe", "bittern", "ibis",
        "curlew", "snipe", "sandpiper", "plover", "lapwing", "avocet", "oystercatcher", "turnstone",
        "godwit", "dowitcher", "phalarope", "jacana", "rail", "coot", "moorhen", "gallinule",
        "pronghorn", "saiga", "springbok", "oryx", "addax", "hartebeest", "topi", "bongo",
        "serval", "caracal", "margay", "bobcat", "wildcat", "ocelot", "cheetah cub", "leopard cub",
        "mouse", "rat", "hamster", "guinea pig", "squirrel", "chipmunk", "hare", "jackrabbit",
        "kangaroo rat", "porpoise", "narwhal", "beluga", "manatee", "dugong", "sea lion", "fur seal",
        "walrus", "otter", "beaver", "muskrat", "nutria", "capybara", "paca", "agouti",
        "chinchilla", "vole", "lemming", "gerbil", "jerboa", "bandicoot", "bilby", "quokka",
        "wombat", "wallaby", "koala", "platypus", "echidna", "aardvark", "hyrax", "civet",
        "fossa", "mongoose", "pangolin", "anteater", "sloth", "tapir", "vicuna", "guanaco",
        "llama", "alpaca", "yak", "muskox", "grayling", "char", "trout", "bass",
        "perch", "barramundi", "piranha", "koi", "goldfish", "betta", "guppy", "minnow",
        "carp", "sturgeon", "catfish", "pollock", "haddock", "codfish", "sole", "halibut",
        "flounder", "stonefish", "lionfish", "pufferfish", "triggerfish", "parrotfish", "angelfish", "tarpon",
        "swordfish", "marlin", "mackerel", "snapper", "grouper", "eel", "moray", "nudibranch",
        "sea slug", "sea cucumber", "urchin", "coral", "anemone", "nautilus", "krill", "barnacle",
        "crayfish", "prawn", "shrimp", "lobster", "crab", "anchovy", "sardine", "herring",
        "cod", "salmon", "tuna", "barracuda", "clownfish", "seahorse", "stingray", "manta",
        "ray", "whale shark",
        
    ],
    "pemandangan": [
        "view", "mountain", "sea", "sunset", "nature", "landscape", "ocean", "scenery",
        "river", "beach", "shore", "lake", "building", "sign", "city", "sky",
        "horizon", "field", "forest", "hill", "valley", "road", "bridge", "village",
        "snow", "ice", "cliff", "rock", "desert", "grass", "sand", "waterfall",
        "skyline", "fence", "path", "trail", "canyon", "ravine", "cave", "dock",
        "pier", "balcony", "sidewalk", "street", "park", "playground", "meadow", "volcano",
        "glacier", "wetland", "ridge", "prairie", "savanna", "tundra", "fountain", "boardwalk",
        "stream", "courtyard", "plaza", "slope", "woods", "pond", "water", "gravel",
        "snowy trail", "dune", "snowy field", "wooden walkway", "marsh", "jungle", "athletic field", "subway platform",
        "rocky beach", "dirt road", "carnival ground", "snowy mountain", "grassy field", "stone wall", "cement wall", "petting zoo",
        "race track", "paved road", "farmland", "drainage pipe", "sandpit", "pool", "ruins", "creek",
        "terrace", "lawn", "residential area", "wooden bench", "rock face", "grassy path", "obstacle course", "play structure",
        "merry-go-round", "stairway", "patio", "pavilion", "wooden deck", "bus shelter", "telephone booth", "art gallery",
        "cement path", "snowy hill", "wooden post", "hurdle", "grassy lane", "bluff", "rocky shore", "pedestrian crossing",
        "tent", "stump", "driveway", "marina", "bleachers", "ramp", "water slide", "jungle gym",
        "zip line", "skate park", "cobbled street", "racetrack", "sandy beach", "riverbank", "wooden bridge", "stone building",
        "outdoor rink", "city street", "forest path", "muddy field", "grassy plain", "rocky cliff", "sandy ground", "urban park",
        "wooden ramp", "concrete ledge", "snowy slope", "dirt track", "coastal rocks", "flower stall", "haystack", "quarry",
        "subway station", "paved lot", "pumpkin patch", "tennis court", "bowling alley", "water park", "wooded area", "grassy yard",
        "dirt path", "shallow pool", "cobblestone plaza", "brick road", "town square", "cement steps", "outdoor staircase", "rural roadway",
        "sandy dune", "wet track", "woodland stream", "cornfield", "cemetery", "driveway", "garage", "wire fence",
        "barbed wire", "park bench", "soccer field", "baseball field", "hockey field", "ice rink", "dirt dune", "mountain vista",
        "rocky path", "grassy knoll", "water slide", "trampoline", "kitchen counter", "barbed wire fence", "shallow water", "grassy park",
        "tiled area", "wooden structure", "dirt hill", "paved street", "urban square", "wooden fence", "sandy shore", "rocky stream",
        "leaf-covered yard", "outdoor pool", "racing track", "stone path", "park pathway", "cement pillar", "train platform", "portable toilet",
        "festival ground", "steep hill", "tire swing", "half-pipe", "cement ramp", "muddy riverbank", "snowy ramp", "outdoor market",
        "concrete path", "urban sidewalk", "grassy countryside", "sand dune", "stone columns", "rural road", "skating ramp", "wooden logs",
        "river shore", "city plaza", "leaf pile", "indoor bar", "casino foyer", "recording studio", "basketball court", "hockey rink",
        "outdoor staircase", "coastal cliff", "concrete debris", "gravel pile", "sheep field", "flag poles", "glass building", "fallen leaves",
        "wooden ramp", "skate park",
        "coastal path", "rocky terrain", "urban beach", "snowy path", "desert trail", "mountain ridge", "grassy meadow", "ocean view",
        "coral reef", "mangrove swamp", "alpine meadow", "coastal dune", "rocky outcrop", "forest clearing", "sandy desert", "tidal pool",
        "estuary", "lagoon", "delta", "bay", "harbor", "inlet", "fjord", "atoll",
        "volcanic rock", "lava field", "geothermal spring", "hot spring", "geyser", "tundra plain", "savanna grassland", "steppe",
        "bamboo grove", "pine forest", "oak grove", "cedar forest", "birch forest", "eucalyptus grove", "rainforest canopy", "jungle trail",
        "waterfront promenade", "urban waterfront", "city park", "rural meadow", "alpine valley", "coastal plain", "desert oasis", "rocky canyon",
        "limestone cliff", "granite rock", "basalt formation", "sandstone ridge", "shale outcrop", "volcanic crater", "glacier lake", "fjord coastline",
        "coral island", "tropical beach", "pebble shore", "shingle beach", "salt marsh", "tidal flat", "mudflat", "marshland",
        "orchid garden", "rose garden", "tulip field", "lavender field", "sunflower field", "vineyard", "orchard", "bamboo forest",
        "cactus desert", "arid plain", "rocky plateau", "windswept cliff", "coastal cave", "limestone cave", "stalactite cave", "stalagmite cave",
        "urban garden", "rooftop garden", "botanical garden", "zen garden", "koi pond", "lily pond", "reflective pool", "ornamental garden",
        "cobblestone path", "gravel walkway", "stone bridge", "wooden pier", "iron bridge", "suspension bridge", "arched bridge", "drawbridge",
        "city harbor", "fishing dock", "marina pier", "coastal boardwalk", "seaside promenade", "cliffside trail", "mountain pass", "snowy ridge",
        "icy slope", "frozen lake", "glacial valley", "tundra landscape", "prairie field", "savanna horizon", "desert expanse",
        "boar", "lynx", "cougar", "ocelot", "caribou", "ant", "mosquito", "gnat",
        "coastal lagoon", "sandy ridge", "pine ridge", "rocky promontory", "tidal marsh", "alpine slope", "grassy ridge", "urban plaza",
        "river delta", "coral atoll", "mangrove forest", "tropical rainforest", "bamboo thicket", "cedar grove", "spruce forest", "heathland",
        "moorland", "peat bog", "salt flat", "arid canyon", "mesa", "butte", "escarpment", "gorge",
        "chasm", "crater lake", "volcanic plain", "ash field", "pumice plain", "glacial moraine", "ice field", "snowfield",
        "taiga", "boreal forest", "alpine tundra", "coastal marsh", "reed bed", "fen", "bog", "swamp",
        "oxbow lake", "braided river", "alluvial plain", "floodplain", "river terrace", "sandbar", "spit", "barrier island",
        "coral cay", "atoll reef", "seagrass meadow", "kelp forest", "tidal basin", "mudflat shore", "shingle coast", "rocky headland",
        "sea stack", "archipelago", "coastal estuary", "fjord inlet", "glacier fjord", "mountain tarn", "alpine lake", "crater rim",
        "volcanic slope", "lava tube", "geothermal field", "sulfur spring", "hot pool", "mud volcano", "saline lake", "dry lake",
        "playa", "salt pan", "dune field", "erg", "badlands", "hoodoo", "rock arch", "natural bridge",
        "karst landscape", "sinkhole", "cenote", "limestone karst", "cave system", "stalagmite chamber", "stalactite grotto", "underground river",
        "coastal terrace", "marine terrace", "wave-cut platform", "sea cliff", "blowhole", "coastal cave", "tidal cave", "coral lagoon",
        "atoll island", "mangrove island", "tropical island", "volcanic island", "coral shore", "black sand beach", "white sand beach", "pebble coast",
        "urban rooftop", "city courtyard", "public garden", "sculpture garden", "water garden", "rock garden", "herb garden", "vegetable patch",
        "flower bed", "hedgerow", "arbor", "trellis", "gazebo", "pergola", "fountain plaza", "reflecting pool",
        "canal", "aqueduct", "reservoir", "dam", "levee", "breakwater", "jetty", "seawall",
        "harbor quay", "marina dock", "fishing pier", "coastal jetty", "promenade pier", "boardwalk path", "cliff trail", "mountain ledge",
        "alpine ridge", "snowy plateau", "glacial cirque", "arete", "col", "saddle", "pass", "highland",
        "lowland", "plain", "plateau", "escarp", "scarp", "talus slope", "scree", "boulder field",
        "river gorge", "canyon rim", "mesa top", "butte ridge", "volcanic cone", "crater edge", "ash plain", "lava plateau",
        "coastal lagoon", "sandy ridge", "pine ridge", "rocky promontory", "tidal marsh", "alpine slope", "grassy ridge", "urban plaza",
        "river delta", "coral atoll", "mangrove forest", "tropical rainforest", "bamboo thicket", "cedar grove", "spruce forest", "heathland",
        "moorland", "peat bog", "salt flat", "arid canyon", "mesa", "butte", "escarpment", "gorge",
        "chasm", "crater lake", "volcanic plain", "ash field", "pumice plain", "glacial moraine", "ice field", "snowfield",
        "taiga", "boreal forest", "alpine tundra", "coastal marsh", "reed bed", "fen", "bog", "swamp",
        "oxbow lake", "braided river", "alluvial plain", "floodplain", "river terrace", "sandbar", "spit", "barrier island",
        "coral cay", "atoll reef", "seagrass meadow", "kelp forest", "tidal basin", "mudflat shore", "shingle coast", "rocky headland",
        "sea stack", "archipelago", "coastal estuary", "fjord inlet", "glacier fjord", "mountain tarn", "alpine lake", "crater rim",
        "volcanic slope", "lava tube", "geothermal field", "sulfur spring", "hot pool", "mud volcano", "saline lake", "dry lake",
        "playa", "salt pan", "dune field", "erg", "badlands", "hoodoo", "rock arch", "natural bridge",
        "karst landscape", "sinkhole", "cenote", "limestone karst", "cave system", "stalagmite chamber", "stalactite grotto", "underground river",
        "coastal terrace", "marine terrace", "wave-cut platform", "sea cliff", "blowhole", "coastal cave", "tidal cave", "coral lagoon",
        "atoll island", "mangrove island", "tropical island", "volcanic island", "coral shore", "black sand beach", "white sand beach", "pebble coast",
        "urban rooftop", "city courtyard", "public garden", "sculpture garden", "water garden", "rock garden", "herb garden", "vegetable patch",
        "flower bed", "hedgerow", "arbor", "trellis", "gazebo", "pergola", "fountain plaza", "reflecting pool",
        "canal", "aqueduct", "reservoir", "dam", "levee", "breakwater", "jetty", "seawall",
        "harbor quay", "marina dock", "fishing pier", "coastal jetty", "promenade pier", "boardwalk path", "cliff trail", "mountain ledge",
        "alpine ridge", "snowy plateau", "glacial cirque", "arete", "col", "saddle", "pass", "highland",
        "lowland", "plain", "plateau", "escarp", "scarp", "talus slope", "scree", "boulder field",
        "river gorge", "canyon rim", "mesa top", "butte ridge", "volcanic cone", "crater edge", "ash plain", "lava plateau",
        
    ],
    "suasana": [
        "calm", "quiet", "peaceful", "relax", "serene", "tranquil", "silence", "mood",
        "atmosphere", "vibe", "ambiance", "energetic", "lively", "playful", "festive", "sunny",
        "snowy", "rainy", "night", "sunlit", "beautiful", "rural", "urban", "crowded",
        "foggy", "stormy", "breezy", "twilight", "dawn", "overcast", "hazy", "vibrant",
        "cloudy", "dark", "bright", "windy", "chilly", "warm", "festive", "clear",
        "crisp", "busy", "joyful", "wintry", "competitive", "relaxed", "autumnal", "cheerful",
        "dusty", "celebratory", "blurry", "summery", "muddy", "neon-lit", "shaded", "smoky",
        "mid-afternoon", "evening", "sunrise", "rainy night", "dusk", "fall", "winter", "tropical",
        "joyful", "athletic", "competitive", "playful", "intense", "adventurous", "thrilling", "nighttime",
        "daytime", "autumn", "summery", "lively", "cheerful", "energetic", "crowded", "dynamic",
        "spirited", "fun", "exciting", "vibrant", "active", "social", "dramatic", "costumed",
        "celebratory", "athletic", "playful", "social", "festive", "joyful", "competitive", "thrilling",
        "adventurous", "lively", "cheerful", "energetic", "dynamic", "spirited", "fun", "relaxed",
        "sunny day", "autumn leaves", "cold", "wet", "intense", "crowded", "dramatic", "smiling",
        "laughing", "posing", "performing", "racing", "whispering", "diving", "swinging",
        "Halloween", "concert", "gymnastic", "skateboarding", "surfing", "motocross", "kayaking", "soccer",
        "rugby", "basketball", "field hockey", "cheering", "festive crowd", "adventurous stunt", "nighttime city", "playful children",
        "competitive race", "thrilling jump", "social gathering", "casual atmosphere", "outdoor fun", "autumn play", "winter sports", "celebratory event",
        "playful children", "competitive race", "thrilling jump", "social gathering", "casual atmosphere", "outdoor fun", "autumn play", "winter sports", 
        "celebratory event", "Halloween", "concert", "gymnastic", "skateboarding", "surfing", "motocross", "kayaking", 
        "soccer", "rugby", "basketball", "field hockey", "cheering", "festive crowd", "adventurous stunt", "nighttime city", 
        "sunny day", "autumn leaves", "cold", "wet", "intense", "crowded", "dramatic", "smiling", 
        "laughing", "posing", "performing", "whispering", "diving", "swinging", "calm", 
        "quiet", "peaceful", "relax", "serene", "tranquil", "silence", "mood", "atmosphere", 
        "vibe", "ambiance", "energetic", "lively", "playful", "festive", "sunny", "snowy", 
        "rainy", "night", "sunlit", "beautiful", "rural", "urban", "crowded", "foggy", 
        "stormy", "breezy", "twilight", "dawn", "overcast", "hazy", "vibrant", "cloudy", 
        "dark", "bright", "warm", "chilly", "festive", "clear", "crisp", "busy", 
        "joyful", "wintry", "competitive", "relaxed", "autumnal", "cheerful", "dusty", "celebratory", 
        "blurry", "summery", "muddy", "neon-lit", "shaded", "smoky", "mid-afternoon", "evening", 
        "sunrise", "rainy night", "dusk", "fall", "winter", "tropical", "joyful", "athletic", 
        "competitive", "playful", "intense", "adventurous", "thrilling", "nighttime", "daytime", "autumn", 
        "summery", "lively", "cheerful", "energetic", "crowded", "dynamic", "spirited", "fun", 
        "exciting", "vibrant", "active", "social", "dramatic", "costumed",
        "festive parade", "joyful celebration", "vibrant festival", "lively street", "cheerful crowd", "dynamic event", "thrilling stunt", "adventurous vibe",
        "moonlit night", "starry sky", "golden hour", "misty morning", "foggy dawn", "hazy afternoon", "warm sunset", "cool twilight",
        "stormy sea", "choppy waves", "turbulent ocean", "breezy shore", "humid day", "arid heat", "frosty morning", "icy chill",
        "lively market", "bustling street", "serene beach", "tranquil forest", "peaceful meadow", "vibrant city", "festive fair", "joyful gathering",
        "autumn breeze", "spring bloom", "summer heat", "winter frost", "snowy silence", "rainy dusk", "overcast sky", "cloudy horizon",
        "energetic race", "competitive match", "spirited performance", "playful romp", "dramatic scene", "thrilling action", "adventurous leap", "intense moment",
        "cozy gathering", "warm ambiance", "lively party", "cheerful reunion", "festive mood", "dynamic crowd", "joyful event", "spirited dance",
        "moonlight glow", "sunrise warmth", "sunset hues", "twilight calm", "starry night", "foggy evening", "misty valley", "dewy morning",
        "windy hill", "stormy cliff", "humid jungle", "arid desert", "frosty field", "snowy quiet", "icy calm", "serene lake",
        "bustling festival", "vibrant parade", "cheerful market", "lively fair", "dynamic rally", "thrilling competition", "adventurous outing", "joyful play",
        "festive night", "cheerful evening", "lively carnival", "bustling fair", "vibrant rally", "joyous parade", "dynamic festival", "spirited event",
        "tranquil dusk", "serene twilight", "misty night", "starlit evening", "golden dusk", "cool evening", "warm twilight", "hazy evening",
        "stormy night", "windy evening", "chilly dusk", "frosty evening", "icy night", "snowy dusk", "crisp night", "clear evening",
        "lively plaza", "bustling market", "cheerful fairground", "vibrant street", "festive market", "joyful carnival", "dynamic gathering", "spirited rally",
        "autumn chill", "spring warmth", "summer breeze", "winter chill", "rainy evening", "foggy night", "dewy dusk", "humid evening",
        "energetic match", "thrilling race", "competitive game", "playful match", "intense competition", "adventurous race", "dramatic moment", "spirited contest",
        "cozy evening", "warm gathering", "lively reunion", "cheerful party", "festive atmosphere", "dynamic performance", "joyful dance", "vibrant show",
        "moonlit evening", "starry dusk", "sunset glow", "twilight haze", "dawn mist", "morning dew", "evening breeze", "night calm",
        "windy night", "stormy evening", "humid night", "arid evening", "frosty dusk", "snowy evening", "icy evening", "serene night",
        "bustling carnival", "vibrant fair", "cheerful festival", "lively parade", "dynamic street", "thrilling event", "adventurous performance", "joyful show",
        "tranquil evening", "peaceful night", "calm dusk", "serene evening", "quiet twilight", "mellow night", "soft evening", "gentle dusk",
        "lively concert", "festive show", "energetic performance", "vibrant dance", "cheerful game", "dynamic match", "spirited race", "thrilling contest",
        "festive parade", "joyful celebration", "vibrant festival", "lively street", "cheerful crowd", "dynamic event", "thrilling stunt", "adventurous vibe",
        "moonlit night", "starry sky", "golden hour", "misty morning", "foggy dawn", "hazy afternoon", "warm sunset", "cool twilight",
        "stormy sea", "choppy waves", "turbulent ocean", "breezy shore", "humid day", "arid heat", "frosty morning", "icy chill",
        "lively market", "bustling street", "serene beach", "tranquil forest", "peaceful meadow", "vibrant city", "festive fair", "joyful gathering",
        "autumn breeze", "spring bloom", "summer heat", "winter frost", "snowy silence", "rainy dusk", "overcast sky", "cloudy horizon",
        "energetic race", "competitive match", "spirited performance", "playful romp", "dramatic scene", "thrilling action", "adventurous leap", "intense moment",
        "cozy gathering", "warm ambiance", "lively party", "cheerful reunion", "festive mood", "dynamic crowd", "joyful event", "spirited dance",
        "moonlight glow", "sunrise warmth", "sunset hues", "twilight calm", "starry night", "foggy evening", "misty valley", "dewy morning",
        "windy hill", "stormy cliff", "humid jungle", "arid desert", "frosty field", "snowy quiet", "icy calm", "serene lake",
        "bustling festival", "vibrant parade", "cheerful market", "lively fair", "dynamic rally", "thrilling competition", "adventurous outing", "joyful play",
        "festive night", "cheerful evening", "lively carnival", "bustling fair", "vibrant rally", "joyous parade", "dynamic festival", "spirited event",
        "tranquil dusk", "serene twilight", "misty night", "starlit evening", "golden dusk", "cool evening", "warm twilight", "hazy evening",
        "stormy night", "windy evening", "chilly dusk", "frosty evening", "icy night", "snowy dusk", "crisp night", "clear evening",
        "lively plaza", "bustling market", "cheerful fairground", "vibrant street", "festive market", "joyful carnival", "dynamic gathering", "spirited rally",
        "autumn chill", "spring warmth", "summer breeze", "winter chill", "rainy evening", "foggy night", "dewy dusk", "humid evening",
        "energetic match", "thrilling race", "competitive game", "playful match", "intense competition", "adventurous race", "dramatic moment", "spirited contest",
        "cozy evening", "warm gathering", "lively reunion", "cheerful party", "festive atmosphere", "dynamic performance", "joyful dance", "vibrant show",
        "moonlit evening", "starry dusk", "sunset glow", "twilight haze", "dawn mist", "morning dew", "evening breeze", "night calm",
        "windy night", "stormy evening", "humid night", "arid evening", "frosty dusk", "snowy evening", "icy evening", "serene night",
        "bustling carnival", "vibrant fair", "cheerful festival", "lively parade", "dynamic street", "thrilling event", "adventurous performance", "joyful show",
        "tranquil evening", "peaceful night", "calm dusk", "serene evening", "quiet twilight", "mellow night", "soft evening", "gentle dusk",
        "lively concert", "festive show", "energetic performance", "vibrant dance", "cheerful game", "dynamic match", "spirited race", "thrilling contest",
        
    ]
}